### ISSUE TITLE
execute 方法 459行 为什么最终返回0

### ISSUE THREAD

**Issue by genius4339** [hyperf/command#3]
src/Command.php   459 行 为什么最后直接返回 0 ？
如果我php脚本异常会导致最终的exitcode是0，然后认为这个脚本是直行正常的

**Comment by huangzhhui** [comment]
正常结束难道不应该返回 0 吗？

**Comment by genius4339** [comment]
如果callback里面返回了一个exception  code 为 -100 那也会返回0

**Comment by limingxinleo** [comment]
因为 run() 方法 拿不到 exit code

这里确实可以优化一下
